export const ACTION_TYPES = {
  GET_EVENTS: "GET_EVENTS",
  GET_EVENTS_ERROR: "GET_EVENTS_ERROR",
  GET_EVENTS_SUCCESS: "GET_EVENTS_SUCCESS",

  CREATE_EVENT: "CREATE_EVENT",
  CREATE_EVENT_SUCCESS: "CREATE_EVENT_SUCCESS",
  CREATE_EVENT_ERROR: "CREATE_EVENT_ERROR",

  DELETE_EVENT: "DELETE_EVENT",
  DELETE_EVENT_SUCCESS: "DELETE_EVENT_SUCCESS",
  DELETE_EVENT_ERROR: "DELETE_EVENT_ERROR",
};
